[package]
name = "cm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = ">=0.26"
speedy2d = "1.4"
base64 = "0.21"
libdeflater = "0.12"
clap = { version = "4.4.8", features = ["derive"] }
